@host=http://localhost:5058
POST {{host}}/api/account/refreshToken
Content-Type: application/json

{
    "RefreshToken" : "4%2BTIw9r2Dv3r%2B2ahN8NAFN23IM7suhDYH9e16OyrOl5C06U61w4zwfTA3cKMWIFm6DY4hr%2Blcew7CeAhrhoZVw%3D%3D"
}