@host=http://localhost:5058

POST {{host}}/api/account/register
Content-Type: application/json

{   
    "Name" : "Rollergod",
    "Password" :"Pa55sw0rd!123",
    "Email" : "Rollergod@yandex.ru",
    "ImageName" : ""
}